<<<<<<< HEAD
MatchingTranslations:
  enabled: false
TemplateLength:
  enabled: false
=======
root: .
include_categories: theme, liquid
exclude_patterns:
  - "node_modules/**"
  - "templates/.gitkeep"
  - "sections/.gitkeep"
  - "snippets/.gitkeep"
  - "assets/.gitkeep"
  - "config/.gitkeep"
>>>>>>> main
