name: CI
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify theme files present
        run: |
          test -f templates/index.json
          test -f assets/viral-beauty-kit.css
          test -f sections/vbk-hero.liquid
          test -f sections/vbk-image-with-text.liquid
          test -f sections/vbk-marquee-badges.liquid
