<<<<<<< HEAD
permissions:
  contents: read
  pull-requests: write
  checks: write

permissions:
  contents: read
  pull-requests: write
  checks: write

name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Lighthouse
        uses: shopify/lighthouse-ci-action@v1
        with:
          store: ${{ secrets.SHOP_STORE_OS2 }}
          password: ${{ secrets.SHOP_PASSWORD_OS2 }}
          access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
          collection_handle: all
          lhci_github_app_token: ${{ secrets.LHCI_GITHUB_TOKEN }}
          pull_theme: ${{ secrets.SHOP_PULL_THEME }}
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}
=======
name: CI
on:
  push: { branches: ['**'] }
  pull_request: { branches: ['**'] }
  workflow_dispatch: {}
permissions: { contents: read }
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify theme files present
        run: |
          test -f layout/theme.liquid || (echo "layout/theme.liquid missing" && exit 1)
          test -f assets/viral-beauty-kit.css || (echo "assets/viral-beauty-kit.css missing" && exit 1)
          test -f sections/vbk-header.liquid || (echo "sections/vbk-header.liquid missing" && exit 1)
          test -f sections/vbk-hero.liquid || (echo "sections/vbk-hero.liquid missing" && exit 1)
>>>>>>> main
