name: Deploy Theme (Staging only)

on:
  # Manual trigger remains available
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to deploy"
        default: "staging"
        required: true
      theme_id:
        description: "Target STAGING Theme ID (unpublished)"
        required: true
  # Auto-deploy on pushes to staging
  push:
    branches:
      - staging

concurrency:
  group: theme-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
    steps:
      # For manual runs, checkout the provided branch; for push, default
      - name: Checkout (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Checkout (push)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Install Shopify CLI
        run: |
          npm i -g @shopify/cli @shopify/theme

      - name: Push to STAGING theme
        env:
          # Required settings for CI auth with Theme Access token
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}     # e.g. store-name.myshopify.com
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
          # Optional secret used for auto-deploy on push
          STAGING_THEME_ID: ${{ secrets.SHOPIFY_STAGING_THEME_ID }}
          # Provided when run manually
          INPUT_THEME_ID: ${{ inputs.theme_id }}
          SHOPIFY_CLI_TTY: 0
        run: |
          set -euo pipefail
          THEME_ID="${INPUT_THEME_ID:-}"
          if [[ -z "$THEME_ID" ]]; then
            THEME_ID="${STAGING_THEME_ID:-}"
          fi
          if [[ -z "$THEME_ID" ]]; then
            echo "Error: Theme ID not provided. Set input 'theme_id' (manual) or secret SHOPIFY_STAGING_THEME_ID (push)." >&2
            exit 1
          fi

          shopify theme push \
            --store "$SHOPIFY_FLAG_STORE" \
            --theme "$THEME_ID" \
            --allow-live \
            --password "$SHOPIFY_CLI_THEME_TOKEN" \
            --json
